//
// Created by sondahi on 17.12.22.
//

#ifndef GEMBEDDED_C_DEVICECONTEXTSTATUS_H
#define GEMBEDDED_C_DEVICECONTEXTSTATUS_H

typedef enum {
    DEVICE_CONTEXT_SUCCESS = 0,
    DEVICE_CONTEXT_LOCK_ERROR = 1,
    DEVICE_CONTEXT_UNLOCK_ERROR = 2,
    DEVICE_CONTEXT_INITIALIZED_ERROR = 3,
    DEVICE_CONTEXT_NOT_INITIALIZED_ERROR = 4,
    DEVICE_CONTEXT_GPIOBASE_ERROR = 5,
    DEVICE_CONTEXT_CLOCKBASE_ERROR = 6,
    DEVICE_CONTEXT_PWMBASE_ERROR = 7,
    DEVICE_CONTEXT_I2CBASE_ERROR = 8,
    DEVICE_CONTEXT_REGISTER_ERROR = 9
} DEVICE_CONTEXT_STATUS;

#endif //GEMBEDDED_C_DEVICECONTEXTSTATUS_H
