//
// Created by sondahi on 15.01.23.
//

#ifndef GEMBEDDED_C_COMMON_PERIPHERAL_H
#define GEMBEDDED_C_COMMON_PERIPHERAL_H

#define CORE_CLOCK_SPEED        (1500000000U)
#define PERIPHERAL_BASE_ADDRESS (0xFE000000U)

#endif //GEMBEDDED_C_COMMON_PERIPHERAL_H
