gcmake_cmake_version=3.22.1
gcmake_project_namespace=gembedded
gcmake_project_name=native
gcmake_project_version=1.0.0
gcmake_project_description=io wrapper for java on linux
gcmake_project_contact=Gokay Comert gokay.comert@icloud.com

gcmake_toolchain_environment=LINUXTOOLCHAIN_HOME
gcmake_gctest_enable=true