//
// Created by sondahi on 28.01.23.
//

#ifndef GEMBEDDED_C_PIN_EXCEPTION_H
#define GEMBEDDED_C_PIN_EXCEPTION_H

#define PIN_CONTROLLER_EXCEPTION_NO_ERROR       (0)
#define PIN_CONTROLLER_INITIALIZED_NO_ERROR           (0)
#define PIN_DRIVER_NOT_INITILIZED_ERROR        (-1)

#define PIN_SESSION_EXCEPTION_NO_ERROR          (0)
#define PIN_SESSION_EXCEPTION_INIT_ERROR        (-1)
#define PIN_SESSION_EXCEPTION_LOCK_ERROR        (-2)
#define PIN_SESSION_EXCEPTION_UNLOCK_ERROR      (-2)
#define PIN_SESSION_EXCEPTION_DESTROY_ERROR     (-2)

#define PIN_VALIDATOR_EXCEPTION_NO_ERROR        (0)
#define PIN_VALIDATOR_EXCEPTION_NUMBER_ERROR    (-1)

#define PIN_DRIVER_EXCEPTION_NO_ERROR           (0)
#define PIN_DRIVER_EXCEPTION_SETUP_ERROR        (-1)
#define PIN_DRIVER_EXCEPTION_SHUTDOWN_ERROR     (-2)

#define PIN_CONFIG_EXCEPTION_NO_ERROR           (-3)
#define PIN_CONFIG_EXCEPTION_FUNCTION_ERROR     (-4)
#define PIN_CONFIG_EXCEPTION_PULLUPDOWN_ERROR   (-5)
#define PIN_CONFIG_EXCEPTION_FILE_ERROR         (-6)
#define PIN_CONFIG_EXCEPTION_IOCTL_ERROR        (-7)
#define PIN_CONFIG_EXCEPTION_EVENT_ERROR        (-8)

#define PIN_IO_EXCEPTION_NO_ERROR               (-9)
#define PIN_IO_EXCEPTION_POLL_IO_ERROR          (-10)
#define PIN_IO_EXCEPTION_POLL_TIMEOUT_ERROR     (-11)
#define PIN_IO_EXCEPTION_FILE_ERROR             (-12)

#define PIN_STORE_EXCEPTION_NO_ERROR            (-13)


#endif //GEMBEDDED_C_PIN_EXCEPTION_H
