//
// Created by sondahi on 30.12.22.
//

#include "gtest/gtest.h"

extern "C" {
#include "pinvalidator.h"
}

TEST(PinValidator, testValidatePin) {

ASSERT_EQ(PIN_VALIDATION_ERROR, validatePin(PIN_TYPE_GPIO, PIN_1));
ASSERT_EQ(PIN_VALIDATION_ERROR, validatePin(PIN_TYPE_CLOCK, PIN_5));
ASSERT_EQ(PIN_VALIDATION_ERROR, validatePin(PIN_TYPE_PWM, PIN_17));
ASSERT_EQ(PIN_VALIDATION_ERROR, validatePin(PIN_TYPE_I2C, PIN_4));
ASSERT_EQ(PIN_VALIDATION_ERROR, validatePin(PIN_TYPE_SPI, PIN_12));
ASSERT_EQ(PIN_VALIDATION_ERROR, validatePin(PIN_TYPE_UART, PIN_16));

ASSERT_EQ(PIN_VALIDATION_SUCCESS, validatePin(PIN_TYPE_GPIO, PIN_4));
ASSERT_EQ(PIN_VALIDATION_SUCCESS, validatePin(PIN_TYPE_CLOCK, PIN_4));
ASSERT_EQ(PIN_VALIDATION_SUCCESS, validatePin(PIN_TYPE_PWM, PIN_18));
ASSERT_EQ(PIN_VALIDATION_SUCCESS, validatePin(PIN_TYPE_I2C, PIN_2));
ASSERT_EQ(PIN_VALIDATION_SUCCESS, validatePin(PIN_TYPE_SPI, PIN_9));
ASSERT_EQ(PIN_VALIDATION_SUCCESS, validatePin(PIN_TYPE_UART, PIN_15));

}