/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_comert_gembedded_device_nativeinterface_PWMDriver */

#ifndef _Included_com_comert_gembedded_device_nativeinterface_PWMDriver
#define _Included_com_comert_gembedded_device_nativeinterface_PWMDriver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_comert_gembedded_device_nativeinterface_PWMDriver
 * Method:    setupPWMMDriver
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_comert_gembedded_device_nativeinterface_PWMDriver_setupPWMMDriver
  (JNIEnv *, jclass);

/*
 * Class:     com_comert_gembedded_device_nativeinterface_PWMDriver
 * Method:    shutdownPWMDriver
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_comert_gembedded_device_nativeinterface_PWMDriver_shutdownPWMDriver
  (JNIEnv *, jclass);

/*
 * Class:     com_comert_gembedded_device_nativeinterface_PWMDriver
 * Method:    configurePWMPin
 * Signature: (Lcom/comert/gembedded/api/device/Pin;Lcom/comert/gembedded/api/device/pwm/PWMMode;Lcom/comert/gembedded/api/device/pwm/PWMPolarity;Lcom/comert/gembedded/api/device/pwm/PWMSilence;I)V
 */
JNIEXPORT void JNICALL Java_com_comert_gembedded_device_nativeinterface_PWMDriver_configurePWMPin
  (JNIEnv *, jclass, jobject, jobject, jobject, jobject, jint);

/*
 * Class:     com_comert_gembedded_device_nativeinterface_PWMDriver
 * Method:    getPWMPinRegisterSelector
 * Signature: (B)B
 */
JNIEXPORT jbyte JNICALL Java_com_comert_gembedded_device_nativeinterface_PWMDriver_getPWMPinRegisterSelector
  (JNIEnv *, jclass, jbyte);

/*
 * Class:     com_comert_gembedded_device_nativeinterface_PWMDriver
 * Method:    enablePWMPin
 * Signature: (B)V
 */
JNIEXPORT void JNICALL Java_com_comert_gembedded_device_nativeinterface_PWMDriver_enablePWMPin
  (JNIEnv *, jclass, jbyte);

/*
 * Class:     com_comert_gembedded_device_nativeinterface_PWMDriver
 * Method:    disablePWMPin
 * Signature: (B)V
 */
JNIEXPORT void JNICALL Java_com_comert_gembedded_device_nativeinterface_PWMDriver_disablePWMPin
  (JNIEnv *, jclass, jbyte);

/*
 * Class:     com_comert_gembedded_device_nativeinterface_PWMDriver
 * Method:    writePWMPinData
 * Signature: (BI)V
 */
JNIEXPORT void JNICALL Java_com_comert_gembedded_device_nativeinterface_PWMDriver_writePWMPinData
  (JNIEnv *, jclass, jbyte, jint);

/*
 * Class:     com_comert_gembedded_device_nativeinterface_PWMDriver
 * Method:    writePWMPinDataWithException
 * Signature: (BI)V
 */
JNIEXPORT void JNICALL Java_com_comert_gembedded_device_nativeinterface_PWMDriver_writePWMPinDataWithException
  (JNIEnv *, jclass, jbyte, jint);

#ifdef __cplusplus
}
#endif
#endif
