/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_comert_gembedded_device_nativeinterface_DeviceDriver */

#ifndef _Included_com_comert_gembedded_device_nativeinterface_DeviceDriver
#define _Included_com_comert_gembedded_device_nativeinterface_DeviceDriver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_comert_gembedded_device_nativeinterface_DeviceDriver
 * Method:    setupDeviceDriver
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_comert_gembedded_device_nativeinterface_DeviceDriver_setupDeviceDriver
  (JNIEnv *, jclass);

/*
 * Class:     com_comert_gembedded_device_nativeinterface_DeviceDriver
 * Method:    shutdownDeviceDriver
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_comert_gembedded_device_nativeinterface_DeviceDriver_shutdownDeviceDriver
  (JNIEnv *, jclass);

/*
 * Class:     com_comert_gembedded_device_nativeinterface_DeviceDriver
 * Method:    getDeviceName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_comert_gembedded_device_nativeinterface_DeviceDriver_getDeviceName
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
