/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_comert_gembedded_device_nativeinterface_GPIODriver */

#ifndef _Included_com_comert_gembedded_device_nativeinterface_GPIODriver
#define _Included_com_comert_gembedded_device_nativeinterface_GPIODriver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_comert_gembedded_device_nativeinterface_GPIODriver
 * Method:    setupGPIODriver
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_comert_gembedded_device_nativeinterface_GPIODriver_setupGPIODriver
  (JNIEnv *, jclass);

/*
 * Class:     com_comert_gembedded_device_nativeinterface_GPIODriver
 * Method:    shutdownGPIODriver
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_comert_gembedded_device_nativeinterface_GPIODriver_shutdownGPIODriver
  (JNIEnv *, jclass);

/*
 * Class:     com_comert_gembedded_device_nativeinterface_GPIODriver
 * Method:    configureInputPin
 * Signature: (Lcom/comert/gembedded/api/device/Pin;Lcom/comert/gembedded/api/device/gpio/PullUpDown;)V
 */
JNIEXPORT void JNICALL Java_com_comert_gembedded_device_nativeinterface_GPIODriver_configureInputPin
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_comert_gembedded_device_nativeinterface_GPIODriver
 * Method:    getInputPinRegisterSelector
 * Signature: (B)B
 */
JNIEXPORT jbyte JNICALL Java_com_comert_gembedded_device_nativeinterface_GPIODriver_getInputPinRegisterSelector
  (JNIEnv *, jclass, jbyte);

/*
 * Class:     com_comert_gembedded_device_nativeinterface_GPIODriver
 * Method:    getInputPinBitField
 * Signature: (B)I
 */
JNIEXPORT jint JNICALL Java_com_comert_gembedded_device_nativeinterface_GPIODriver_getInputPinBitField
  (JNIEnv *, jclass, jbyte);

/*
 * Class:     com_comert_gembedded_device_nativeinterface_GPIODriver
 * Method:    configureListenerPin
 * Signature: (Lcom/comert/gembedded/api/device/Pin;Lcom/comert/gembedded/api/device/gpio/Event;ILcom/comert/gembedded/api/device/gpio/ListenerCallBack;)V
 */
JNIEXPORT void JNICALL Java_com_comert_gembedded_device_nativeinterface_GPIODriver_configureListenerPin
  (JNIEnv *, jclass, jobject, jobject, jint, jobject);

/*
 * Class:     com_comert_gembedded_device_nativeinterface_GPIODriver
 * Method:    getListenerPinRegisterSelector
 * Signature: (B)B
 */
JNIEXPORT jbyte JNICALL Java_com_comert_gembedded_device_nativeinterface_GPIODriver_getListenerPinRegisterSelector
  (JNIEnv *, jclass, jbyte);

/*
 * Class:     com_comert_gembedded_device_nativeinterface_GPIODriver
 * Method:    configureOutputPin
 * Signature: (Lcom/comert/gembedded/api/device/Pin;)V
 */
JNIEXPORT void JNICALL Java_com_comert_gembedded_device_nativeinterface_GPIODriver_configureOutputPin
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_comert_gembedded_device_nativeinterface_GPIODriver
 * Method:    getOutputPinRegisterSelector
 * Signature: (B)B
 */
JNIEXPORT jbyte JNICALL Java_com_comert_gembedded_device_nativeinterface_GPIODriver_getOutputPinRegisterSelector
  (JNIEnv *, jclass, jbyte);

/*
 * Class:     com_comert_gembedded_device_nativeinterface_GPIODriver
 * Method:    getOutputPinBitField
 * Signature: (B)I
 */
JNIEXPORT jint JNICALL Java_com_comert_gembedded_device_nativeinterface_GPIODriver_getOutputPinBitField
  (JNIEnv *, jclass, jbyte);

/*
 * Class:     com_comert_gembedded_device_nativeinterface_GPIODriver
 * Method:    isPinHigh
 * Signature: (BI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_comert_gembedded_device_nativeinterface_GPIODriver_isPinHigh
  (JNIEnv *, jclass, jbyte, jint);

/*
 * Class:     com_comert_gembedded_device_nativeinterface_GPIODriver
 * Method:    isPinLow
 * Signature: (BI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_comert_gembedded_device_nativeinterface_GPIODriver_isPinLow
  (JNIEnv *, jclass, jbyte, jint);

/*
 * Class:     com_comert_gembedded_device_nativeinterface_GPIODriver
 * Method:    setPinHigh
 * Signature: (BI)V
 */
JNIEXPORT void JNICALL Java_com_comert_gembedded_device_nativeinterface_GPIODriver_setPinHigh
  (JNIEnv *, jclass, jbyte, jint);

/*
 * Class:     com_comert_gembedded_device_nativeinterface_GPIODriver
 * Method:    setPinHighWithException
 * Signature: (BI)V
 */
JNIEXPORT void JNICALL Java_com_comert_gembedded_device_nativeinterface_GPIODriver_setPinHighWithException
  (JNIEnv *, jclass, jbyte, jint);

/*
 * Class:     com_comert_gembedded_device_nativeinterface_GPIODriver
 * Method:    setPinLow
 * Signature: (BI)V
 */
JNIEXPORT void JNICALL Java_com_comert_gembedded_device_nativeinterface_GPIODriver_setPinLow
  (JNIEnv *, jclass, jbyte, jint);

/*
 * Class:     com_comert_gembedded_device_nativeinterface_GPIODriver
 * Method:    setPinLowWithException
 * Signature: (BI)V
 */
JNIEXPORT void JNICALL Java_com_comert_gembedded_device_nativeinterface_GPIODriver_setPinLowWithException
  (JNIEnv *, jclass, jbyte, jint);

/*
 * Class:     com_comert_gembedded_device_nativeinterface_GPIODriver
 * Method:    pollPin
 * Signature: (B)V
 */
JNIEXPORT void JNICALL Java_com_comert_gembedded_device_nativeinterface_GPIODriver_pollPin
  (JNIEnv *, jclass, jbyte);

/*
 * Class:     com_comert_gembedded_device_nativeinterface_GPIODriver
 * Method:    releasePin
 * Signature: (B)V
 */
JNIEXPORT void JNICALL Java_com_comert_gembedded_device_nativeinterface_GPIODriver_releasePin
  (JNIEnv *, jclass, jbyte);

#ifdef __cplusplus
}
#endif
#endif
