/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_comert_gembedded_device_nativeinterface_JNIUtil */

#ifndef _Included_com_comert_gembedded_device_nativeinterface_JNIUtil
#define _Included_com_comert_gembedded_device_nativeinterface_JNIUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_comert_gembedded_device_nativeinterface_JNIUtil
 * Method:    setupJNIUtil
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_comert_gembedded_device_nativeinterface_JNIUtil_setupJNIUtil
  (JNIEnv *, jclass);

/*
 * Class:     com_comert_gembedded_device_nativeinterface_JNIUtil
 * Method:    shutdownJNIUtil
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_comert_gembedded_device_nativeinterface_JNIUtil_shutdownJNIUtil
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
